//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twinder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Twinder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twinder.
        /// </summary>
        public static string app_title {
            get {
                return ResourceManager.GetString("app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new account.
        /// </summary>
        public static string btn_add_new_account {
            get {
                return ResourceManager.GetString("btn_add_new_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Error.
        /// </summary>
        public static string btn_copy_error {
            get {
                return ResourceManager.GetString("btn_copy_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string btn_ok {
            get {
                return ResourceManager.GetString("btn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btn_save {
            get {
                return ResourceManager.GetString("btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string chat_btn_send_message {
            get {
                return ResourceManager.GetString("chat_btn_send_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations.
        /// </summary>
        public static string command_open_recommendations {
            get {
                return ResourceManager.GetString("command_open_recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Location.
        /// </summary>
        public static string command_set_location {
            get {
                return ResourceManager.GetString("command_set_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string command_user_profile {
            get {
                return ResourceManager.GetString("command_user_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common friends.
        /// </summary>
        public static string common_friends_count {
            get {
                return ResourceManager.GetString("common_friends_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common likes.
        /// </summary>
        public static string common_likes_count {
            get {
                return ResourceManager.GetString("common_likes_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading matches....
        /// </summary>
        public static string download_data_matches {
            get {
                return ResourceManager.GetString("download_data_matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading recommendations....
        /// </summary>
        public static string download_data_recs {
            get {
                return ResourceManager.GetString("download_data_recs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading user....
        /// </summary>
        public static string download_data_user {
            get {
                return ResourceManager.GetString("download_data_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured.
        /// </summary>
        public static string error_exception_occured {
            get {
                return ResourceManager.GetString("error_exception_occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string fblogin_btn_cancel {
            get {
                return ResourceManager.GetString("fblogin_btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ID.
        /// </summary>
        public static string fblogin_btn_get_id {
            get {
                return ResourceManager.GetString("fblogin_btn_get_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Token.
        /// </summary>
        public static string fblogin_btn_get_token {
            get {
                return ResourceManager.GetString("fblogin_btn_get_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string fblogin_btn_ok {
            get {
                return ResourceManager.GetString("fblogin_btn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FB ID.
        /// </summary>
        public static string fblogin_id {
            get {
                return ResourceManager.GetString("fblogin_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FB Token.
        /// </summary>
        public static string fblogin_token {
            get {
                return ResourceManager.GetString("fblogin_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string filer_gender_header {
            get {
                return ResourceManager.GetString("filer_gender_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string filter_age_header {
            get {
                return ResourceManager.GetString("filter_age_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string filter_age_max_age {
            get {
                return ResourceManager.GetString("filter_age_max_age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string filter_age_min_age {
            get {
                return ResourceManager.GetString("filter_age_min_age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string filter_description_both {
            get {
                return ResourceManager.GetString("filter_description_both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string filter_description_header {
            get {
                return ResourceManager.GetString("filter_description_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes words.
        /// </summary>
        public static string filter_description_includes {
            get {
                return ResourceManager.GetString("filter_description_includes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With description only.
        /// </summary>
        public static string filter_description_with_bio {
            get {
                return ResourceManager.GetString("filter_description_with_bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without description only.
        /// </summary>
        public static string filter_description_without_bio {
            get {
                return ResourceManager.GetString("filter_description_without_bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string filter_messages_apply {
            get {
                return ResourceManager.GetString("filter_messages_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total message count.
        /// </summary>
        public static string filter_messages_count {
            get {
                return ResourceManager.GetString("filter_messages_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string filter_messages_header {
            get {
                return ResourceManager.GetString("filter_messages_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes words.
        /// </summary>
        public static string filter_messages_includes {
            get {
                return ResourceManager.GetString("filter_messages_includes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string filter_name_hint {
            get {
                return ResourceManager.GetString("filter_name_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string filter_reset {
            get {
                return ResourceManager.GetString("filter_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string filter_show_filters {
            get {
                return ResourceManager.GetString("filter_show_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole words.
        /// </summary>
        public static string filter_whole_words {
            get {
                return ResourceManager.GetString("filter_whole_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download _Matches.
        /// </summary>
        public static string force_matches {
            get {
                return ResourceManager.GetString("force_matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download _Full Match Data.
        /// </summary>
        public static string force_matches_full {
            get {
                return ResourceManager.GetString("force_matches_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download _Recommendations.
        /// </summary>
        public static string force_recs {
            get {
                return ResourceManager.GetString("force_recs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string gender_both {
            get {
                return ResourceManager.GetString("gender_both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man.
        /// </summary>
        public static string gender_man {
            get {
                return ResourceManager.GetString("gender_man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        public static string gender_men {
            get {
                return ResourceManager.GetString("gender_men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woman.
        /// </summary>
        public static string gender_woman {
            get {
                return ResourceManager.GetString("gender_woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        public static string gender_women {
            get {
                return ResourceManager.GetString("gender_women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download _Full Data.
        /// </summary>
        public static string match_context_menu_download_full {
            get {
                return ResourceManager.GetString("match_context_menu_download_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open _Chat.
        /// </summary>
        public static string match_context_menu_open_chat {
            get {
                return ResourceManager.GetString("match_context_menu_open_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string match_context_menu_open_folder {
            get {
                return ResourceManager.GetString("match_context_menu_open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open _Profile.
        /// </summary>
        public static string match_context_menu_open_profile {
            get {
                return ResourceManager.GetString("match_context_menu_open_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Unmatch.
        /// </summary>
        public static string match_context_menu_unmatch {
            get {
                return ResourceManager.GetString("match_context_menu_unmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio.
        /// </summary>
        public static string match_info_bio {
            get {
                return ResourceManager.GetString("match_info_bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string match_info_job {
            get {
                return ResourceManager.GetString("match_info_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last message.
        /// </summary>
        public static string match_info_last_message {
            get {
                return ResourceManager.GetString("match_info_last_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen.
        /// </summary>
        public static string match_info_last_seen {
            get {
                return ResourceManager.GetString("match_info_last_seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched on.
        /// </summary>
        public static string match_info_matched_on {
            get {
                return ResourceManager.GetString("match_info_matched_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string match_info_message_count {
            get {
                return ResourceManager.GetString("match_info_message_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        public static string match_info_school {
            get {
                return ResourceManager.GetString("match_info_school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched on.
        /// </summary>
        public static string matched_on {
            get {
                return ResourceManager.GetString("matched_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_winder.
        /// </summary>
        public static string menu_app {
            get {
                return ResourceManager.GetString("menu_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string menu_app_exit {
            get {
                return ResourceManager.GetString("menu_app_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string menu_help {
            get {
                return ResourceManager.GetString("menu_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string menu_help_about {
            get {
                return ResourceManager.GetString("menu_help_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string menu_tools {
            get {
                return ResourceManager.GetString("menu_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Login.
        /// </summary>
        public static string menu_tools_login {
            get {
                return ResourceManager.GetString("menu_tools_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Account.
        /// </summary>
        public static string menu_tools_switch_account {
            get {
                return ResourceManager.GetString("menu_tools_switch_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string recs_button_like {
            get {
                return ResourceManager.GetString("recs_button_like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Like.
        /// </summary>
        public static string recs_button_like_super {
            get {
                return ResourceManager.GetString("recs_button_like_super", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string recs_button_next {
            get {
                return ResourceManager.GetString("recs_button_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string recs_button_pass {
            get {
                return ResourceManager.GetString("recs_button_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string recs_button_prev {
            get {
                return ResourceManager.GetString("recs_button_prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default.
        /// </summary>
        public static string set_as_default {
            get {
                return ResourceManager.GetString("set_as_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error locating.
        /// </summary>
        public static string set_location_auto_detect_error {
            get {
                return ResourceManager.GetString("set_location_auto_detect_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locating....
        /// </summary>
        public static string set_location_auto_detecting {
            get {
                return ResourceManager.GetString("set_location_auto_detecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Location.
        /// </summary>
        public static string set_location_btn_auto_detect {
            get {
                return ResourceManager.GetString("set_location_btn_auto_detect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Ascending.
        /// </summary>
        public static string sort_activity_asc {
            get {
                return ResourceManager.GetString("sort_activity_asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Descending.
        /// </summary>
        public static string sort_activity_desc {
            get {
                return ResourceManager.GetString("sort_activity_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched On Ascending.
        /// </summary>
        public static string sort_matched_asc {
            get {
                return ResourceManager.GetString("sort_matched_asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched On Descending.
        /// </summary>
        public static string sort_matched_desc {
            get {
                return ResourceManager.GetString("sort_matched_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Ascending.
        /// </summary>
        public static string sort_name_asc {
            get {
                return ResourceManager.GetString("sort_name_asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Descending.
        /// </summary>
        public static string sort_name_desc {
            get {
                return ResourceManager.GetString("sort_name_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered matches.
        /// </summary>
        public static string statusbar_filtered_count {
            get {
                return ResourceManager.GetString("statusbar_filtered_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string statusbar_match_count {
            get {
                return ResourceManager.GetString("statusbar_match_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations.
        /// </summary>
        public static string statusbar_rec_count {
            get {
                return ResourceManager.GetString("statusbar_rec_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string tinder_auth_connecting {
            get {
                return ResourceManager.GetString("tinder_auth_connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error.
        /// </summary>
        public static string tinder_auth_error {
            get {
                return ResourceManager.GetString("tinder_auth_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string tinder_auth_okay {
            get {
                return ResourceManager.GetString("tinder_auth_okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting matches and recommendations....
        /// </summary>
        public static string tinder_getting_recs_matches {
            get {
                return ResourceManager.GetString("tinder_getting_recs_matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations error.
        /// </summary>
        public static string tinder_recs_error {
            get {
                return ResourceManager.GetString("tinder_recs_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new recommendations.
        /// </summary>
        public static string tinder_recs_exchausted {
            get {
                return ResourceManager.GetString("tinder_recs_exchausted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting recommendations....
        /// </summary>
        public static string tinder_recs_getting_recs {
            get {
                return ResourceManager.GetString("tinder_recs_getting_recs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting matches....
        /// </summary>
        public static string tinder_update_getting_matches {
            get {
                return ResourceManager.GetString("tinder_update_getting_matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting matches.
        /// </summary>
        public static string tinder_update_matches_error {
            get {
                return ResourceManager.GetString("tinder_update_matches_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show profile.
        /// </summary>
        public static string tooltip_show_profile {
            get {
                return ResourceManager.GetString("tooltip_show_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total messages.
        /// </summary>
        public static string total_messages {
            get {
                return ResourceManager.GetString("total_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum age.
        /// </summary>
        public static string user_age_filter_max {
            get {
                return ResourceManager.GetString("user_age_filter_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum age.
        /// </summary>
        public static string user_age_filter_min {
            get {
                return ResourceManager.GetString("user_age_filter_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interested in.
        /// </summary>
        public static string user_interested_in {
            get {
                return ResourceManager.GetString("user_interested_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max distance, km.
        /// </summary>
        public static string user_max_distance {
            get {
                return ResourceManager.GetString("user_max_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last active.
        /// </summary>
        public static string user_tinder_active {
            get {
                return ResourceManager.GetString("user_tinder_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tinder created on.
        /// </summary>
        public static string user_tinder_created {
            get {
                return ResourceManager.GetString("user_tinder_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tinder pinged on.
        /// </summary>
        public static string user_tinder_pinged {
            get {
                return ResourceManager.GetString("user_tinder_pinged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string window_title_chat {
            get {
                return ResourceManager.GetString("window_title_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Data.
        /// </summary>
        public static string window_title_download_data {
            get {
                return ResourceManager.GetString("window_title_download_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string window_title_error {
            get {
                return ResourceManager.GetString("window_title_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Login.
        /// </summary>
        public static string window_title_fblogin {
            get {
                return ResourceManager.GetString("window_title_fblogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string window_title_my_profile {
            get {
                return ResourceManager.GetString("window_title_my_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string window_title_profile {
            get {
                return ResourceManager.GetString("window_title_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations.
        /// </summary>
        public static string window_title_recommendations {
            get {
                return ResourceManager.GetString("window_title_recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Location.
        /// </summary>
        public static string window_title_set_location {
            get {
                return ResourceManager.GetString("window_title_set_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Account.
        /// </summary>
        public static string window_title_switch_account {
            get {
                return ResourceManager.GetString("window_title_switch_account", resourceCulture);
            }
        }
    }
}
