//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twinder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Twinder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twinder.
        /// </summary>
        public static string app_title {
            get {
                return ResourceManager.GetString("app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error.
        /// </summary>
        public static string auth_connect_error {
            get {
                return ResourceManager.GetString("auth_connect_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string auth_connecting {
            get {
                return ResourceManager.GetString("auth_connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting matches.
        /// </summary>
        public static string auth_get_matches_error {
            get {
                return ResourceManager.GetString("auth_get_matches_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting matches....
        /// </summary>
        public static string auth_getting_matches {
            get {
                return ResourceManager.GetString("auth_getting_matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string auth_okay {
            get {
                return ResourceManager.GetString("auth_okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common friends.
        /// </summary>
        public static string common_friends_count {
            get {
                return ResourceManager.GetString("common_friends_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common likes.
        /// </summary>
        public static string common_likes_count {
            get {
                return ResourceManager.GetString("common_likes_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen.
        /// </summary>
        public static string last_seen {
            get {
                return ResourceManager.GetString("last_seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched on.
        /// </summary>
        public static string matched_on {
            get {
                return ResourceManager.GetString("matched_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_winder.
        /// </summary>
        public static string menu_app {
            get {
                return ResourceManager.GetString("menu_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string menu_app_exit {
            get {
                return ResourceManager.GetString("menu_app_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string menu_help {
            get {
                return ResourceManager.GetString("menu_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string menu_help_about {
            get {
                return ResourceManager.GetString("menu_help_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string menu_tools {
            get {
                return ResourceManager.GetString("menu_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Login.
        /// </summary>
        public static string menu_tools_login {
            get {
                return ResourceManager.GetString("menu_tools_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        public static string school {
            get {
                return ResourceManager.GetString("school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string statusbar_match_count {
            get {
                return ResourceManager.GetString("statusbar_match_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total messages.
        /// </summary>
        public static string total_messages {
            get {
                return ResourceManager.GetString("total_messages", resourceCulture);
            }
        }
    }
}
